allowMergeCommits: true
allowRevertCommits: true
titleAndCommits: true

# Any changes should also me made on the [commitizen script](#/scripts/commitizen.js)
types:
  - feat
  - fix
  - style
  - refactor
  - perf
  - test
  - build
  - docs
  - chore
