version: '2'
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
plugins:
  eslint:
    enabled: true
    channel: 'eslint-6'
    exclude_patterns:
      - '.cache/'
      - '.cache-jest/'
      - 'coverage/'
      - 'node_modules/'
      - '.eslintcache'
      - '!src/**/*.ts'
      - '!src/**/*.js'
      - '!tests/**/*.ts'
      - '!scripts/**/*.ts'
      - '!scripts/**/*.js'
exclude_patterns:
  - '.cache/'
  - '.cache-jest/'
  - 'coverage/'
  - 'node_modules/'
  - '.eslintcache'
  - '**.spec.ts'
  - '**/__mocks__/'
  - 'dist/'
