name: 'Stale and close'
description: 'A GitHub action to stale and close automatically your issues and pull requests.'
author: 'C0ZEN'
inputs:
  github-token:
    description: 'A GitHub token used to perform the API calls to GitHub through `@actions/github`. Usually `{{ secrets.GITHUB_TOKEN }}`.'
    required: false
    default: ${{ github.token }}
  dry-run:
    description: 'A mode where any Data Manipulation Language will be skipped. Useful to debug.'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
