coverage:
  range: 50..95
  round: down
  precision: 2
comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  branches:
    - 'master'
    - 'develop'
