# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  PreJob:
    runs-on: ubuntu-latest
    outputs:
      SHOULD_SKIP: ${{ steps.skip-check.outputs.should_skip }}
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          concurrent_skipping: 'same_content_newer'
  Lint:
    needs: PreJob
    if: ${{ needs.PreJob.outputs.SHOULD_SKIP != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.22.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint ts
        run: npm run lint:ts:ci
      - name: Lint other
        run: npm run lint:other:ci
  CoverageCodeClimate:
    needs: PreJob
    if: ${{ needs.PreJob.outputs.SHOULD_SKIP != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.22.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Cache Jest
        id: cache-jest
        uses: actions/cache@v2
        env:
          cache-name: cache-jest-cc
        with:
          path: .cache-jest
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/jest.config.js') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        with:
          coverageCommand: npm run test:ci:coverage
          debug: true
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  IntegrationCoverageCodecov:
    needs: PreJob
    if: ${{ needs.PreJob.outputs.SHOULD_SKIP != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.22.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Cache Jest
        id: cache-jest
        uses: actions/cache@v2
        env:
          cache-name: cache-jest-integration
        with:
          path: .cache-jest
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/jest.config.js') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Test
        run: npm run test:ci:coverage:integration
      - name: Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: integration
          name: Stale
  UnitCoverageCodecov:
    needs: PreJob
    if: ${{ needs.PreJob.outputs.SHOULD_SKIP != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.22.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Cache Jest
        id: cache-jest
        uses: actions/cache@v2
        env:
          cache-name: cache-jest-unit
        with:
          path: .cache-jest
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/jest.config.js') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Test
        run: npm run test:ci:coverage:unit
      - name: Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unit
          name: Stale
  Build:
    needs: PreJob
    if: ${{ needs.PreJob.outputs.SHOULD_SKIP != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.22.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build:dirty
        env:
          CI: true
      - name: Differences
        id: verify-changed-files
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            git diff
            echo "dist has changed. Run the npm script build locally to build the distribution and then push the changes."
            exit 1
          fi
