name: Deploy website
on:
  workflow_dispatch:
jobs:
  Website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2
        with:
          node-version: 14.17.6
          cache: npm
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # renovate: tag=v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            documentation/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm ci
          cd documentation
          npm ci
      - name: Build website
        run: |
          cd documentation
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # renovate: tag=v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/build
          user_name: ${{ secrets.GIT_COMMITTER_NAME }}
          user_email: ${{ secrets.GIT_COMMITTER_EMAIL }}
