name: Deploy website
on:
  workflow_dispatch:
jobs:
  GitHubWebsite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: 16.16.0
          cache: npm
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            documentation/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm ci
          cd documentation
          npm ci
      - name: Build website
        run: |
          cd documentation
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935 # tag=v3
        with:
          github_token: ${{ secrets.SONIA_BOT_GH_TOKEN }}
          publish_dir: ./documentation/build
          user_name: ${{ secrets.GIT_COMMITTER_NAME }}
          user_email: ${{ secrets.GIT_COMMITTER_EMAIL }}
  VercelWebsite:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - name: Install Vercel
        run: |
          npm i vercel
      - name: Pull Vercel
        run: |
          npm run vercel:pull:ci -- --environment=production --token ${{ secrets.VERCEL_LOGIN }}
      - name: Build Vercel
        run: |
          npm run build:docs:vercel -- --prod --token ${{ secrets.VERCEL_LOGIN }}
      - name: Deploy Vercel
        run: |
          npm run deploy:vercel -- --prebuilt --prod --token ${{ secrets.VERCEL_LOGIN }}
