name: Deploy website
on:
  workflow_dispatch:
jobs:
  Website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: 16.16.0
          cache: npm
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@f4278025ab0f432ce369118909e46deec636f50c # tag=v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            documentation/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm ci
          cd documentation
          npm ci
      - name: Build website
        run: |
          cd documentation
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # renovate: tag=v3
        with:
          github_token: ${{ secrets.SONIA_BOT_GH_TOKEN }}
          publish_dir: ./documentation/build
          user_name: ${{ secrets.GIT_COMMITTER_NAME }}
          user_email: ${{ secrets.GIT_COMMITTER_EMAIL }}
