name: Deploy website
on:
  workflow_dispatch:
jobs:
  GitHubWebsite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 16.16.0
          cache: npm
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            documentation/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm ci
          cd documentation
          npm ci
      - name: Build website
        run: |
          cd documentation
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          github_token: ${{ secrets.SONIA_BOT_GH_TOKEN }}
          publish_dir: ./documentation/build
          user_name: ${{ secrets.GIT_COMMITTER_NAME }}
          user_email: ${{ secrets.GIT_COMMITTER_EMAIL }}
  VercelWebsite:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Install Vercel
        run: |
          npm i vercel
      - name: Pull Vercel
        run: |
          npm run vercel:pull:ci -- --environment=production --token ${{ secrets.VERCEL_LOGIN }}
      - name: Build Vercel
        run: |
          npm run build:docs:vercel -- --prod --token ${{ secrets.VERCEL_LOGIN }}
      - name: Deploy Vercel
        run: |
          npm run deploy:vercel -- --prebuilt --prod --token ${{ secrets.VERCEL_LOGIN }}
