# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Labeler
on:
  - pull_request
jobs:
  Labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@e54d1c08bb51b1826c8da4b05eb3fbfbc5cc4943 # renovate: tag=v3
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
