name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  CurrentTag:
    runs-on: ubuntu-latest
    outputs:
      CURRENT_TAG: ${{ steps.save-current-tag.outputs.CURRENT_TAG }}
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Reset branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Get current tag
        id: current-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1.1.0
        with:
          fallback: 1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save current tag
        id: save-current-tag
        run: echo '::set-output name=CURRENT_TAG::${{ steps.current-tag.outputs.tag }}'
  Release:
    runs-on: ubuntu-latest
    needs: [CurrentTag]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.22.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.22.x
          cache: npm
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            documentation/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm ci
          cd documentation
          npm ci
      - name: Build
        run: npm run build
        env:
          CI: true
      - name: Release
        run: npm run semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  Website:
    runs-on: ubuntu-latest
    needs: [CurrentTag, Release]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.6
          cache: npm
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build website
        working-directory: documentation
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/build
          # Assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
  PR:
    runs-on: ubuntu-latest
    needs: [CurrentTag, Release]
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Reset branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show current tag
        run: echo 'The current tag is ${{ needs.CurrentTag.outputs.CURRENT_TAG }}'
      - name: Has same tag
        if: needs.CurrentTag.outputs.CURRENT_TAG == steps.latest-tag.outputs.tag
        run: echo 'The current tag did not change'
      - name: Has new tag
        if: needs.CurrentTag.outputs.CURRENT_TAG != steps.latest-tag.outputs.tag
        run: echo 'The current tag is not the same after the release. A new tag has been created'
      - name: Create PR from master to develop
        if: needs.CurrentTag.outputs.CURRENT_TAG != steps.latest-tag.outputs.tag
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'chore(develop): merge master into develop due to new version ${{ steps.latest-tag.outputs.tag }}'
          branch: feature/merge-master-into-develop
          assignees: C0ZEN
          labels: auto-merge
          commit-message: 'chore(develop): merge master into develop'
          body: |
            :tada: This PR was generated after the creation of the version ${{ steps.latest-tag.outputs.tag }} :tada:

            The release is available on:
            - [npm package (@latest dist-tag)](https://www.npmjs.com/package/@sonia-corporation/stale/v/${{ steps.latest-tag.outputs.tag }})
            - [GitHub release](https://github.com/Sonia-corporation/stale/releases/tag/${{ steps.latest-tag.outputs.tag }})

            Your **github-actions** bot :rocket:
