name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  NODE_VERSION: '14.17.6'
jobs:
  CurrentTag:
    runs-on: ubuntu-latest
    outputs:
      CURRENT_TAG: ${{ steps.save-current-tag.outputs.CURRENT_TAG }}
    steps:
      - name: Checkout develop
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          ref: develop
      - name: Reset branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Get current tag
        id: current-tag
        uses: WyriHaximus/github-action-get-previous-tag@8a0e045f02c0a3a04e1452df58b90fc7e555e950 # renovate: tag=v1.1.0
        with:
          fallback: 1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SONIA_BOT_GH_TOKEN }}
      - name: Save current tag
        id: save-current-tag
        run: echo '::set-output name=CURRENT_TAG::${{ steps.current-tag.outputs.tag }}'
  Release:
    runs-on: ubuntu-latest
    needs: [CurrentTag]
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09 # tag=v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            documentation/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm ci
          cd documentation
          npm ci
      - name: Build
        run: npm run build
        env:
          CI: true
      - name: Release
        run: npm run semver
        env:
          GITHUB_TOKEN: ${{ secrets.SONIA_BOT_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
  Website:
    runs-on: ubuntu-latest
    needs: [CurrentTag, Release]
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          # Since the previous job (Release) is doing a commit containing the new website changelog
          # We need to specify exactly the ref so that we are sure to load the last commit from the branch
          ref: master
      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09 # tag=v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            documentation/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm ci
          cd documentation
          npm ci
      - name: Build website
        run: |
          cd documentation
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # renovate: tag=v3
        with:
          github_token: ${{ secrets.SONIA_BOT_GH_TOKEN }}
          publish_dir: ./documentation/build
          user_name: ${{ secrets.GIT_COMMITTER_NAME }}
          user_email: ${{ secrets.GIT_COMMITTER_EMAIL }}
  PR:
    runs-on: ubuntu-latest
    needs: [CurrentTag, Release]
    steps:
      - name: Checkout develop
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          ref: develop
      - name: Reset branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@8a0e045f02c0a3a04e1452df58b90fc7e555e950 # renovate: tag=v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.SONIA_BOT_GH_TOKEN }}
      - name: Show current tag
        run: echo 'The current tag is ${{ needs.CurrentTag.outputs.CURRENT_TAG }}'
      - name: Has same tag
        if: needs.CurrentTag.outputs.CURRENT_TAG == steps.latest-tag.outputs.tag
        run: echo 'The current tag did not change'
      - name: Has new tag
        if: needs.CurrentTag.outputs.CURRENT_TAG != steps.latest-tag.outputs.tag
        run: echo 'The current tag is not the same after the release. A new tag has been created'
      - name: Create PR from master to develop
        if: needs.CurrentTag.outputs.CURRENT_TAG != steps.latest-tag.outputs.tag
        uses: peter-evans/create-pull-request@bd72e1b7922d417764d27d30768117ad7da78a0e # tag=v4
        with:
          token: ${{ secrets.SONIA_BOT_GH_TOKEN }}
          title: 'chore(develop): merge master into develop due to new version ${{ steps.latest-tag.outputs.tag }}'
          branch: feature/merge-master-into-develop
          assignees: C0ZEN
          labels: 'auto-merge :ok:'
          commit-message: 'chore(develop): merge master into develop'
          committer: ${{ secrets.GIT_COMMITTER_NAME }} <${{ secrets.GIT_COMMITTER_EMAIL }}>
          author: ${{ secrets.GIT_AUTHOR_NAME }} <${{ secrets.GIT_AUTHOR_EMAIL }}>
          body: |
            :tada: This PR was generated after the creation of the version ${{ steps.latest-tag.outputs.tag }} :tada:

            The release is available on:
            - [npm package (@latest dist-tag)](https://www.npmjs.com/package/@sonia-corporation/stale/v/${{ steps.latest-tag.outputs.tag }})
            - [GitHub release](https://github.com/Sonia-corporation/stale/releases/tag/${{ steps.latest-tag.outputs.tag }})

            Your **@Sonia-corporation-bot** :rocket:
