name: Stale tester
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
jobs:
  Stale:
    runs-on: ubuntu-latest
    name: Run dry-run stale # Test to run the current local stale action in dry-run mode (to detect possible issues)
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Stale
        id: stale
        uses: ./
        with:
          dry-run: true
          issue-stale-label: 'stale :cold_face:'
          pull-request-stale-label: 'stale :cold_face:'
