name: Stale tester
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
jobs:
  Stale:
    runs-on: ubuntu-latest
    name: Run dry-run stale # Test to run the current local stale action in dry-run mode (to detect possible issues)
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - name: Stale
        id: stale
        uses: ./
        with:
          dry-run: true
          issue-stale-label: 'stale :cold_face:'
          pull-request-stale-label: 'stale :cold_face:'
