name: Stale
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
jobs:
  Stale:
    runs-on: ubuntu-latest
    name: Run stale
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Stale
        id: stale
        uses: sonia-corporation/stale@develop
        with:
          issue-ignore-any-labels: |
            frozen
            help wanted
            dependency-fix
            dependencies
