name: Stale
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
jobs:
  Stale:
    runs-on: ubuntu-latest
    name: Run stale
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Stale
        id: stale
        uses: sonia-corporation/stale@develop
        with:
          issue-days-before-stale: 30
          issue-days-before-close: 10
          issue-ignore-any-labels: |
            frozen :ice_cube:
            waiting :hourglass:
            help wanted :sos:
            dependency-fix :wrench:
            dependencies :package:
          issue-ignore-any-assignees: |
            C0ZEN
          issue-stale-comment: |
            [~frozen :ice_cube:]: https://img.shields.io/badge/-frozen-D6FFFA.svg
            [~waiting :hourglass:]: https://img.shields.io/badge/-waiting-F5CD79.svg
            [~dependency-fix :wrench:]: https://img.shields.io/badge/-dependency%20fix-c44569.svg
            [~dependencies :package:]: https://img.shields.io/badge/-dependencies-1e3799.svg
            [~help wanted :sos:]: https://img.shields.io/badge/-help%20wanted-63cdda.svg

            :warning: **Warning!** :warning:
            This issue was marked as stale due to a lack of activity for 30 days. :worried:
            In 10 days, this issue will be closed if there is no more activity during this period. :grimacing:

            If you want to avoid this stale state you could add one of these labels:
            - [![label: frozen :ice_cube:][~frozen :ice_cube:]](https://github.com/Sonia-corporation/stale/labels/frozen%20%3Aice_cube%3A)
            - [![label: waiting :hourglass:][~waiting :hourglass:]](https://github.com/Sonia-corporation/stale/labels/waiting%20%3Ahourglass%3A)
            - [![label: dependency-fix :wrench:][~dependency-fix :wrench:]](https://github.com/Sonia-corporation/stale/labels/dependency-fix%20%3Awrench%3A)
            - [![label: dependencies :package:][~dependencies :package:]](https://github.com/Sonia-corporation/stale/labels/dependencies%20%3Apackage%3A)
            - [![label: help wanted :sos:][~help wanted :sos:]](https://github.com/Sonia-corporation/stale/labels/help%20wanted%20%3Asos%3A)
          issue-close-comment: |
            :warning: **Warning!** :warning:
            This issue was closed due to a lack of activity for 10 days after it was stale. :worried:
          issue-stale-label: 'stale :cold_face:'
          pull-request-days-before-stale: 30
          pull-request-days-before-close: 10
          pull-request-ignore-any-labels: |
            frozen :ice_cube:
            waiting :hourglass:
            help wanted :sos:
            dependency-fix :wrench:
            dependencies :package:
          pull-request-ignore-any-assignees: |
            C0ZEN
          pull-request-stale-comment: |
            [~frozen :ice_cube:]: https://img.shields.io/badge/-frozen-D6FFFA.svg
            [~waiting :hourglass:]: https://img.shields.io/badge/-waiting-F5CD79.svg
            [~dependency-fix :wrench:]: https://img.shields.io/badge/-dependency%20fix-c44569.svg
            [~dependencies :package:]: https://img.shields.io/badge/-dependencies-1e3799.svg
            [~help wanted :sos:]: https://img.shields.io/badge/-help%20wanted-63cdda.svg

            :warning: **Warning!** :warning:
            This pull request was marked as stale due to a lack of activity for 30 days. :worried:
            In 10 days, this pull request will be closed if there is no more activity during this period. :grimacing:

            If you want to avoid this stale state you could add one of these labels:
            - [![label: frozen :ice_cube:][~frozen :ice_cube:]](https://github.com/Sonia-corporation/stale/labels/frozen%20%3Aice_cube%3A)
            - [![label: waiting :hourglass:][~waiting :hourglass:]](https://github.com/Sonia-corporation/stale/labels/waiting%20%3Ahourglass%3A)
            - [![label: dependency-fix :wrench:][~dependency-fix :wrench:]](https://github.com/Sonia-corporation/stale/labels/dependency-fix%20%3Awrench%3A)
            - [![label: dependencies :package:][~dependencies :package:]](https://github.com/Sonia-corporation/stale/labels/dependencies%20%3Apackage%3A)
            - [![label: help wanted :sos:][~help wanted :sos:]](https://github.com/Sonia-corporation/stale/labels/help%20wanted%20%3Asos%3A)
          pull-request-close-comment: |
            :warning: **Warning!** :warning:
            This pull request was closed due to a lack of activity for 10 days after it was stale. :worried:
          pull-request-stale-label: 'stale :cold_face:'
